project: 
  type: website
  output-dir: docs
  
website: 
  title: "Ricarda's Advanced GitHub Notes"
  navbar: 
   background: primary
   search: true
  
format: 
  html:
     theme: slate 
  
  
  
  